version: "3.7"

services:
    # Aplicação
    api:
        container_name: "nwl04-api"
        restart: always
        build: .
        ports:
            - ${PORT_APP}:${PORT_APP}
        volumes:
            - ./:/app/nwl04_api
