version: "3.7"

services:
    # Aplicação
    api:
        container_name: "nlw04-nodejs"
        restart: always
        build: .
        ports:
            - ${PORT_APP}:${PORT_APP}
        volumes:
            - ./:/app/nlw04_nodejs
